/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT SC_master.cdb */

/*  Include Header Files  */
#include <std.h>
#include <prd.h>
#include <hst.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <sem.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern PRD_Obj PRD_TimeBase2ms;
extern PRD_Obj PRD_TimeBase20ms;
extern PRD_Obj PRD_TimeBase500ms;
extern HST_Obj RTA_fromHost;
extern HST_Obj RTA_toHost;
extern SWI_Obj PRD_swi;
extern SWI_Obj KNL_swi;
extern TSK_Obj TSK_idle;
extern TSK_Obj TSK_MasterStates;
extern TSK_Obj TSK_MPPT;
extern TSK_Obj TSK_GridPeriodCalc;
extern TSK_Obj TSK_SpiComm;
extern TSK_Obj TSK_SCIb_Update;
extern TSK_Obj TSK_PowerCalc;
extern LOG_Obj LOG_system;
extern LOG_Obj trace;
extern SEM_Obj SEM_TskSpiCommReady;
extern SEM_Obj SEM_TskMasterStatesReady;
extern SEM_Obj SEM_TskMPPTReady;
extern SEM_Obj SEM_TskGridPeriodCalcReady;
extern SEM_Obj SEM_TskSCIbUpdateReady;
extern SEM_Obj SEM_TskPowerCalcReady;
extern SEM_Obj SEM_SPIa;
extern STS_Obj IDL_busyObj;


#ifdef __cplusplus
}
#endif /* extern "C" */
