/***********************************************************************
 *    FILENAME : main.c
 *
 *    PURPOSE  : This file includes initializtion of Slave CPU.
 *    HISTORY  :
 *           DATE            VERSION            AUTHOR            NOTE
 *	
 * 	Software Development Evironment: 
 *	-- CCS 3.3.83.19
 * 	-- BIOS 5.41.02.14
 *	-- Code Generation Tool v5.2.5
 ************************************************************************/

//###########################################################################
// $Release Date: 
//###########################################################################
// Header files
#include "SL_slave.h"

extern Uint16 g_SCICommCnt;
//--- Global variables

/*==========================================*/ 
//--- Global functions
/*==========================================*/ 
//extern Uint16 Orig_epromflg;
/**********************************************************************
* FUNCION   : main()
* PURPOSE   : Initializtion of slave CPU. 
* INPUT     : NA
* RETURN    : void
* CALLS     : void
* CALLED BY :
**********************************************************************/
void main(void)
{
// Step 1. Initialize System Control:
	InitSysCtrl();
	DINT;
// Step 2. Initalize GPIO:
	InitGpio();

// Step 3. Initialize PIE control registers:
// All PIE interrupts disabled and flags are cleared.
	InitPieCtrl();

// Step 4. Initialize peripheral clock:
	InitPeripheralClocks();

// Step 5. User specific code:
	memcpy(&RamfuncsRunStart, &RamfuncsLoadStart, (Uint32)&RamfuncsLoadSize);
	InitFlash();
	memcpy(&ControlLoopInRAMRunStart, &ControlLoopInRAMLoadStart, (Uint32)&ControlLoopInRAMLoadSize);

// Step 6. Initialize peripherals:
	Adc_PowerOn();
	AdcOffsetSelfCal(); 
	InitAdc();
	InitEPwm();
	SysParamDefault(); 
	InitSpi();//
	InitSci();
	InitI2C();

//	EINT;	// Enable Global interrupt INTM
	ERTM;   // Enable Global realtime interrupt DBGM

	PWMOutputsDisable();
//	PWMOutputsEnable();
	EnableInterrupts();

//	S_DC_Fan_Enable;
	GpioDataRegs.GPASET.bit.GPIO2 = 1;

//	Orig_epromflg = 0x00;	
//	s_StateCheck.bit.Resetflg = 0xff;
//	s_StateCheck.Word.byte4 = 0xFF;
//	s_StateCheck.Word.byte5 = 0x07;
}	// end of main()

/**********************************************************************
* PRD_TimeBase2ms function
* Post SEM_StateSwitch_2msPRD when periodic timerBase of 2ms is ready,
* used for state switching.
**********************************************************************/
void PRD_F_TimeBase2ms(void)
{
	SEM_post(&SEM_StateSwitch_2msPRD);
}

/**********************************************************************
* PRD_TimeBase500ms function
* Post SEM_LINa_500msPRD when periodic timerBase of 500ms is ready,
* used for LINa.
**********************************************************************/

void PRD_F_TimeBase500ms(void)
{
	static Uint16 ExitSCiFaultCnt = 0;
	if(0 == s_SysFaultMessage.bit.SciCommLose)
	{
		if(g_SCICommCnt > 40)
		{
			s_SysFaultMessage.bit.SciCommLose = 1;
		}
	}
	else
	{
		if(g_SCICommCnt < 4)
		{
			ExitSCiFaultCnt++;
			if(ExitSCiFaultCnt > 12)
			{
				s_SysFaultMessage.bit.SciCommLose = 0;
				ExitSCiFaultCnt = 0;
			}
		}
	}
	g_SCICommCnt++;
//	AdcRegs.ADCSOCFRC1.bit.SOC15 = 1;	// for test
}

/**********************************************************************
* SPIb task function
**********************************************************************/
void TSK_F_SPIb(void)
{
	while(1)
	{
		SEM_pend(&SEM_SPIb, SYS_FOREVER);

		SetSlaveValue();
		SpiSlaveUpdateData();
		ConsistentCheck();
	}
}

/**********************************************************************
* Executed before main()
**********************************************************************/
void UserInit(void)
{
	extern Uint16 trcdata_loadstart;
	extern Uint16 trcdata_loadsize;
	extern Uint16 trcdata_runstart;
// Section .trcdata is generated by DSP/BIOS.
// It must be copied from its load to its run address BEFORE main().
	memcpy(&trcdata_runstart, &trcdata_loadstart, (Uint32)&trcdata_loadsize);

}	// end of UserInit()
void SysParamDefault(void)
{
	s_SysFaultMessage_Enable.bit.ConsistentFault_VGrid = 1;
	s_SysFaultMessage_Enable.bit.ConsistentFault_FGrid = 0;
	s_SysFaultMessage_Enable.bit.ConsistentFault_DCI = 1;
	s_SysFaultMessage_Enable.bit.ConsistentFault_GFCI = 1;
	s_SysFaultMessage_Enable.bit.OverTempFault_Inv = 1;
	s_SysFaultMessage_Enable.bit.OverTempFault_Boost = 1;
	s_SysFaultMessage_Enable.bit.OverTempFault_Env = 1;
	s_SysFaultMessage_Enable.bit.MChip_Fault = 1;
	s_SysFaultMessage_Enable.bit.HWADFault_VGRID = 0;
	s_SysFaultMessage_Enable.bit.HWADFault_VINV = 0;
	s_SysFaultMessage_Enable.bit.HWADFault_DCI = 0;
	s_SysFaultMessage_Enable.bit.HWADFault_GFCI = 0;
//	s_SysFaultMessage_Enable.bit.DcFan1Fault = 0;
//	s_SysFaultMessage_Enable.bit.DcFan2Fault = 0;


	s_SysFaultMessage.Word.byte0 = 0;
	s_SysFaultMessage.Word.byte1 = 0;
	s_SysFaultMessage.Word.byte2 = 0;
	s_SysFaultMessage.Word.byte3 = 0;
	s_SysFaultMessage.Word.byte4 = 0;
	s_SysFaultMessage.Word.byte5 = 0;
	s_SysFaultMessage.Word.byte6 = 0;
	s_SysFaultMessage.Word.byte7 = 0;
	s_SysFaultMessage.Word.unrecover0 = 0;
	s_SysFaultMessage.Word.unrecover1 = 0;
	s_SysCurrentState = WaitState;

	ADGain.i16VGRID_R = 2257;//9060;
	ADGain.i16VGRID_S = 2257;//9060;
	ADGain.i16VGRID_T = 2257;//9060;	

	ADGain.i16VINV_R = 2180;//9060;
	ADGain.i16VINV_S = 2180;//9060;
	ADGain.i16VINV_T = 2180;//9060;	

	ADGain.i16DCI_R = 3428;//2019;
	ADGain.i16DCI_S = 3428;//2019;
	ADGain.i16DCI_T = 3428;//2019;	

	ADGain.i16VPV1 = 10375;//10263;
	ADGain.i16VPV2 = 10375;//10263;
	ADOffsetSum.i16VPV1 = 0;
	ADOffsetSum.i16VPV2 = 0;

	ADGain.i16VISO1 = 3000; 
	ADGain.i16VISO2	= 3000;

	ADGain.i16GFCI       = 1976;

	ADGain.i16TempAmb    = 3000;
	ADGain.i16TempINVR   = 3000;			
	ADGain.i16TempBoost2 = 4095;
	ADGain.i16TempINVT   = 3000;			
	ADGain.i16TempBoost1 = 4095;
	ADGain.i16TempINVS   = 3000;
	
	s_StateCheck.bit.Zero_Crossing_Flag = 0;
	s_StateCheck.Word.byte0 = 0;
	s_StateCheck.Word.byte1 = 0;
	s_StateCheck.Word.byte2 = 0;
	s_StateCheck.Word.byte3 = 0;
	s_StateCheck.Word.byte4 = 0;//0xFF;//0;
	s_StateCheck.Word.byte5 = 0;//0x3F;//0;
	s_StateCheck.bit.Grid_Pos_Flag = 1;
	s_StateCheck.bit.Grid_Neg_Flag = 1;	
	
	CalcResultAve.i16TempINVR = 20;
	CalcResultAve.i16TempINVS = 20;
	CalcResultAve.i16TempINVT = 20;
	CalcResultAve.i16TempAmb = 20;
	CalcResultAve.i16TempBoost1 = 20;
	
	CalcResultAve.i16VPV1 = 0;
	CalcResultAve.i16VPV2 = 0;	
	
	ADChannelOffset.i16VGRID_R = 0;
	ADChannelOffset.i16VGRID_S = 0;
	ADChannelOffset.i16VGRID_T = 0;	
	ADChannelOffset.i16VINV_R = 0;
	ADChannelOffset.i16VINV_S = 0;
	ADChannelOffset.i16VINV_T = 0;	
	ADChannelOffset.i16DCI_R = 0;
	ADChannelOffset.i16DCI_S = 0;
	ADChannelOffset.i16DCI_T = 0;
	ADChannelOffset.i16GFCI = 0;

	s_StateCheck.bit.DC_Fan_State = 1;
	
	ReactiveValue.i32ReactivedynamicCos1 = 0x01000000;
	ReactiveValue.i32ReactivedynamicCos2 = 0x01000000;
	ReactiveValue.i32ReactivedynamicCos3 = 0x01000000;
	ReactiveValue.i32ReactivedynamicCos4 = 0x01000000;
	ReactiveValue.i32ReactivefixedCos = 0x01000000;
	ReactiveValue.u8ReactivedynamicValue1 = 0;
	ReactiveValue.u8ReactivedynamicValue2 = 20;
	ReactiveValue.u8ReactivedynamicValue3 = 50;
	ReactiveValue.u8ReactivedynamicValue4 = 100;
	ReactiveValue.u8ReactiveMode1 = 0x11;
	ReactiveValue.u8ReactiveMode2 = 0x55;
	ReactiveValue.u8ReactiveMode3 = 0x55;
	ReactiveValue.u8ReactiveMode4 = 0x55;
	ReactiveValue.u8ReactiveMode5 = 0x55;

	s_StateCheck.bit.AcRlyCheckOver = 0;
	
	ProcessVariable.i16ISOCheckMode_Input = 0;
	ProcessVariable.i16IsoCheckcount = 0;
	ProcessVariable.i16IsoCheckStep = 0;
	ProcessVariable.i16TAmbOTP = 78;
	ProcessVariable.i16TInvOTP = 95;
	ProcessVariable.i16TNTCOTP = 80;
	
	s_StateCheck.bit.PLLOver = 0;
	s_StateCheck.bit.AD_initial = 1;
	
	ADOffsetSum.i32VGRID_R = 0;
	ADOffsetSum.i32VGRID_S = 0;
	ADOffsetSum.i32VGRID_T = 0;

	ADOffsetSum.i32VINV_R = 0;
	ADOffsetSum.i32VINV_S = 0;
	ADOffsetSum.i32VINV_T = 0;

	ADOffsetSum.i32DCI_R = 0;
	ADOffsetSum.i32DCI_S = 0;
	ADOffsetSum.i32DCI_T = 0;

	ADOffsetSum.i32GFCI = 0;
	CalcResultAve.i16lost = 0;	

	ProcessVariable.i16InvPowerMode = 0x10;	
	CalcResultAve.i16VISO1_testoutput1 = 12000;	
	CalcResultAve.i16VISO1_testoutput2 = 12000;	
	CalcResultAve.i16VISO1_testoutput3 = 12000;	

	ISO1_RELAY_OFF = 1;			
	ISO2_RELAY_OFF = 1;
	SafetyIsoIslandandSoOnTable[2] = 1;//
	SafetyIsoIslandandSoOnTable[3] = 1000;//
	s_StateCheck.bit.HandShakeOver = 0;
}
//===========================================================================
// No more.
//===========================================================================

