/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT F28035_BIOS_flash.cdb */

/*  Include Header Files  */
#include <std.h>
#include <prd.h>
#include <hst.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <sem.h>
#include <lck.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern PRD_Obj PRD_TimeBase2ms;
extern PRD_Obj PRD_TimeBase500ms;
extern HST_Obj RTA_fromHost;
extern HST_Obj RTA_toHost;
extern SWI_Obj PRD_swi;
extern SWI_Obj KNL_swi;
extern SWI_Obj SWI_I2Ca;
extern TSK_Obj TSK_idle;
extern TSK_Obj TSK_StateSwitch;
extern TSK_Obj TSK_SPIb;
extern TSK_Obj TSK_SCIa;
extern TSK_Obj TSK_GridPeriodCalc;
extern LOG_Obj LOG_system;
extern SEM_Obj SEM_GridPeriod;
extern SEM_Obj SEM_SPIb;
extern SEM_Obj SEM_SCIa;
extern SEM_Obj SEM_StateSwitch_2msPRD;
extern SEM_Obj SEM_TskGridPeriodCalcReady;
extern SEM_Obj SEM_I2C_isr;
extern LCK_Obj LCK_EEPROM;
extern STS_Obj IDL_busyObj;


#ifdef __cplusplus
}
#endif /* extern "C" */
