/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT F28035_BIOS_flash.cdb */

/*  Include Header File  */
#include "F28035_BIOS_flashcfg.h"

/*  Config Structures */
/*  Handles  */
